# First Stage: Build Stage
FROM python:3.10-alpine AS builder

# Install build dependencies for compiling packages
RUN apk add --no-cache gcc musl-dev libffi-dev postgresql-dev

# Set the working directory and install dependencies
WORKDIR /app
COPY config/other_configs/requirements.txt .

# Install Python dependencies in a local directory
RUN pip install --user --no-cache-dir -r requirements.txt

# Final Stage: Runtime Stage
FROM python:3.10-alpine

# Set the working directory
WORKDIR /app

# Copy installed dependencies from the builder
COPY --from=builder /root/.local /root/.local

# Update PATH to include local user-installed packages
ENV PATH=/root/.local/bin:$PATH

# Copy application code from the build stage
COPY src/ src/

# Expose the necessary port
EXPOSE 5001

# Run the application
CMD ["python", "src/bot.py"]
